updates to lots of flag stuff

diff --git a/ewc b/ewc
--- a/ewc
+++ b/ewc
@@ -31,24 +31,30 @@ get_version() {
 
 help_message() {
   echo "
-Usage: ewc <flags> <file.epub>  
+Usage: ewc <-vhbfVt> <file>  
 Purpose: determines the number of words in an epub file
-  -v,       Show version information and exit
-  -h,       Show this help message and exit
+  -v, --version		Show version information and exit
+  -h, --help		Show this help message and exit
 Future supported flags:
-  -b,       Enable batch mode (allow multiple files)
-  -t,       Disable TTY check (allow piping)"
+  -b, --batch		Enable batch mode (allow multiple files)
+  -f, --file		Read file names from a text file (one file per line)
+  -V, --verbose		Enable verbose output (show processing details)
+  -t, --tty			Disable TTY check (allow piping)"
   exit $EXIT_CODE
 }
 
 enable_tty_check() {
-   if [[ $flag_t -eq 1 ]]; then
-      echo "TTY enabled." >&2
-    else
-      echo "Error: TTY disabled." >&2
-      EXIT_CODE=2
-      exit $EXIT_CODE
-    fi
+  if [[ $flag_t -eq 1 ]]; then
+    echo "+TTY enabled."
+  else
+    echo "Error: TTY disabled." >&2
+    EXIT_CODE=2
+    exit $EXIT_CODE
+  fi
+}
+
+file_mode() {
+  echo "File mode support coming soon."
 }
 
 # TODO add multiple file support
@@ -57,15 +63,16 @@ batch_mode() {
 }
 
 check_file() {
-for arg in "$@"; do  # TODO feed this with only the files, not the flags
-  if [[ -f "$arg" && $(file --mime-type "$arg") == *"epub"* ]]; then
-    FILE="$arg"
-  else
-    echo "Error: File $arg not found or invalid file type." >&2
-    EXIT_CODE=3
-    exit $EXIT_CODE
-  fi
-done
+  for arg in "$@"; do  
+    if [[ -f "$arg" && "$(file --mime-type "$arg")" == *"epub"* ]]; then
+      echo $"FILE = $arg"
+      FILE="$arg"
+    else
+      echo "Error: File $arg not found or invalid file type." >&2
+      EXIT_CODE=3
+      exit $EXIT_CODE
+    fi
+  done
 }
 
 count_words() {
@@ -86,36 +93,44 @@ count_words() {
 
 main() {
 
-  ### ARGS AND FLAGS ###
+	### ARGS AND FLAGS ###
 
-  #set local variables
-  local flag_t=0  # flag - TTY 
-  local flag_v=0  # flag - version 
-  local flag_h=0  # flag - help
-  local flag_b=0  # flag - batch mode
-  local POSITIONAL_ARGS=()  # array to hold non-flag arguments (file names)
-  
+	#set local variables
+	local flag_t=0  # flag - TTY 
+	local flag_v=0  # flag - version 
+	local flag_h=0  # flag - help
+	local flag_b=0  # flag - batch mode
+	local flag_f=0  # flag - read from file
+	local flag_V=0  # flag - verbose mode
+	local POSITIONAL_ARGS=()  # array to hold non-flag arguments (file names)
 
-  [[ $# == 0 ]] && flag_h=1  # catch no arguments and show help message
-  # TODO rewrite as "for arg in $@; do", shift, and new array for file names
-  # TODO add support for long flags
-  while getopts ":tbhv" opt; do  
-    case $opt in
-      t)  flag_t=1 ;;
-      b)  flag_b=1 ;;
-      h)  flag_h=1 ;;
-      v)  flag_v=1 ;;
-      ?)  echo "Invalid option: -$OPTARG" >&2 ;;
-    esac
-  done
 
-  [[ $flag_h -eq 1 ]] && help_message && exit $EXIT_CODE
+	#[[ $# == 0 ]] && flag_h=1  # catch no arguments and show help message
+
+	# TODO add support for long flags
+	for arg in $@; do
+		case $arg in 
+    		-t|--tty)  		flag_t=1 ;;
+    		-b|--batch)  	flag_b=1 ;;
+    		-h|--help)  	flag_h=1 ;;
+    		-v|--version)	flag_v=1 ;;
+			-f|--file)		flag_f=1 ;;
+			-V|--verbose)	flag_V=1 ;;
+    		*)  			POSITIONAL_ARGS+=("$arg") ;;
+    	esac
+    done
+
+  [[ $flag_h -eq 1 ]] && help_message 
   [[ $flag_v -eq 1 ]] && get_version && exit $EXIT_CODE
+  [[ $flag_t -eq 1 ]] && enable_tty_check
+  [[ $flag_f -eq 1 ]] && file_mode
   [[ $flag_b -eq 1 ]] && batch_mode
   [[ ! -t 1 ]] && enable_tty_check
 
+
+  echo ${POSITIONAL_ARGS[@]}
   ### MAIN LOGIC ###
-  check_file "$@"
+  check_file ${POSITIONAL_ARGS[@]}
   # FILE_NAME=$(basename "$FILE") 
   # Welcome message
   # count_words "$FILE"
